version: '3.8'

services:
  backend:
    build:
      context: ./backend
      args:
        NODE_ENV: development
    image: e-commerce-backend:1.0.0
    command: npm run dev
    ports:
      - '5000:5000'
      - '9229:9229' # Port 9229 is the default NodeJS debugging port.
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file: ./backend/.env
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dbUser
      - MONGO_INITDB_ROOT_PASSWORD=dbPassword
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
