version: "3.8"

services:
  backend:
    build:
      context: ./backend
      args:
        NODE_ENV: development
    image: ecommerce-backend:1.0.0
    container_name: ecommerce-be
    command: yarn run dev
    ports:
      - '5200:5000'
      - '9229:9229' # Port 9229 is the default NodeJS debugging port.
    volumes:
      - ./backend:/home/app
      - /home/app/node_modules
    env_file: ./backend/.env
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      args:
        NODE_ENV: development
    image: ecommerce-frontend:1.0.0
    container_name: ecommerce-fe
    volumes:
      - ./frontend:/home/app
      - /home/app/node_modules
    ports:
      - 3000:3000
      - 3200:3000
    environment:
      - WATCHPACK_POLLING=true

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dbUser
      - MONGO_INITDB_ROOT_PASSWORD=dbPassword
    volumes:
      - mongo-db:/data/db
    ports:
      - 27017:27017

volumes:
  mongo-db:
