apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongo
  template:
    metadata:
      labels:
        service: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          resources:
            requests:
              memory: "200Mi"
              cpu: "0.3"
            limits:
              memory: "400Mi"
              cpu: "0.5"
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: password
          volumeMounts:
            - name: mongo-volume-mount
              mountPath: /var/lib/mongo/data
      volumes:
        - name: mongo-volume-mount
          persistentVolumeClaim:
            claimName: mongo-pvc
      restartPolicy: Always
